### ISSUE TITLE
Incomplete chain issue

### ISSUE THREAD

**Issue by Cool-Programmer** [kevinkassimo/vhttps#1]
Hello.
I'm not sure if this is an issue or not, i just really need help. So please be kind :)
I've installed and implemented this module with vhost on express. Everything works just perfect, but when i run an ssl test or access the website from phone (?!) it gives me invalid cert error, more accuratley - incomplete chain issue (using letsencrypt)

`
const domain1_opt = {
  hostname: 'sub1.domain.com',
  cert: fs.readFileSync(path.join(__dirname, '../../etc/letsencrypt/live/sub1.domain.com/cert.pem')),
  key: fs.readFileSync(path.join(__dirname, '../../etc/letsencrypt/live/sub1.domain.com/privkey.pem')),
  ca: fs.readFileSync(path.join(__dirname, '../../etc/letsencrypt/live/sub1.domain.com/fullchain.pem'))
};

const domain2_opt = {
  hostname: 'sub2.domain.com',
  cert: fs.readFileSync(path.join(__dirname, '../../etc/letsencrypt/live/sub2.domain.com/cert.pem')),
  key: fs.readFileSync(path.join(__dirname, '../../etc/letsencrypt/live/sub2.domain.com/privkey.pem')),
  ca: fs.readFileSync(path.join(__dirname, '../../etc/letsencrypt/live/sub2.domain.com/fullchain.pem'))
};
`
I suspect there might be something wrong with the code above...
Please help

**Comment by kevinkassimo** [comment]
Hey there. Have you tried removing `ca` from the contexts? It is only supposed to be given if the CA is not well known, in this case LetsEncrypt cross-signed DST root, so there should be no issue to leave the field unspecified. On the other hand, `fullchain.pem` is basically a concatenation of `cert.pem` and `chain.pem`, so this format might not be expected by Node

**Comment by kevinkassimo** [comment]
Also as a ref, [https://gist.github.com/davestevens/c9e437afbb41c1d5c3ab](this guide) uses `chain.pem` (Instead of `full chain.pem`) for `ca`. Not tested myself, but might work. Though I would suggest leaving out the field as not quite necessary

**Comment by Cool-Programmer** [comment]
Hi again, thank you very much for your answer.
Before using `fullchain.pem`, i was using the `chain.pem` file and getting the same incomplete cert. error.
Unfortunately, removing the `ca` part did not help, i'm still getting the same error.
Also facebook debugger also complains with **Curl Error : SSL_CACERT SSL certificate problem: unable to get local issuer certificate**
I know you don't have to help me in this case, because it's just a casual error, but if you find something out please let me know

**Comment by Cool-Programmer** [comment]
Dear @kevinkassimo 
After digging very very deep into letsencrypt's documentation, i found a 3 years old post that helped me a lot :D 

It turns out switching everything's order sometimes helps:
     const second_options = {
         hostname: 'sub.domain.com',
         key: fs.readFileSync(path.join(__dirname, '../../etc/letsencrypt/live/sub.hostname.com/privkey.pem')),
         cert: fs.readFileSync(path.join(__dirname, '../../etc/letsencrypt/live/sub.hostname.com/fullchain.pem')),
         ca: fs.readFileSync(path.join(__dirname, '../../etc/letsencrypt/live/sub.hostname.com/chain.pem'))
    };
This is how it worked, i thought someone may find it useful...

**Comment by kevinkassimo** [comment]
@Cool-Programmer Thanks for the update. This is indeed a quite interesting observation. Probably related to Node's internal implementation.
